### ISSUE TITLE
Running examples on Mac

### ISSUE THREAD

**Issue by srik901** [commaai/body-jim#3]
To run the random_walk.py example

I had to change the following 
env = BodyEnv(body_ip, cameras, render_mode="human")

to
env = BodyEnv(body_ip, cameras,["accelerometer", "gyroscope", "gpsLocation"], render_mode="human")

if not I was getting a time out error. The same thing was happening for the follow_human.py example also

Also to run the follow_human.py I had to install the following that were previously not installed with "pip install bodyjim"
cv2, onnx, onnxruntime

**Comment by fredyshox** [comment]
Which openpilot version/commit are you running?

**Comment by srik901** [comment]
> Which openpilot version/commit are you running on the body?

Latest 0.9.6

**Comment by fredyshox** [comment]
It seems like this is an issue with webrtcd shipped in 0.9.6 and was fixed with https://github.com/commaai/openpilot/commit/09e73f8fb6b681512b1adbe46b2d6e64f0f5f54f. Can you try with the current `master`?

**Comment by srik901** [comment]
Just tested with master and it is working. Thanks!
