### ISSUE TITLE
trying to pair comma body 

### ISSUE THREAD

**Issue by srik901** [commaai/body-jim#5]
I get an "error - try again" when trying to pair comma body with my account. This is with master-ci branch.

**Comment by fredyshox** [comment]
whats your dongle id?

**Comment by srik901** [comment]
080891f86ae006f1

**Comment by sshane** [comment]
This isn't an issue with the body-jim and isn't the appropriate place to report as an issue. It looks like an email ending in `.edu` is already paired with the account. Support should handle this for you.
