### ISSUE TITLE
Test all supported Python versions in CI

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/body-jim#9]
Add a matrix to the `test` CI job to run on all supported Python versions: https://github.com/commaai/body-jim/blob/2f06d4038c6d440ad2b023c4d2e8848e7d41423c/.github/workflows/tests.yaml#L6

GitHub has some docs here: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#using-multiple-python-versions

**Comment by lsrugo** [comment]
I'm going to take a shot at a dynamic implementation (as mentioned in Discord)
